### ISSUE TITLE
Tags and series link to 404

### ISSUE THREAD

**Issue by kaselis** [brandtkeller/personal-blog#1]
Hi Brandt, clicking on series or tags directs to 404 pages, eg this is the url after clicking on kubecon tag:

https://brandtkeller.com/posts/open-source/conference-tips/tags/kubecon

Clicking on series has the same issue, links to relative page rather than absolute.

**Comment by brandtkeller** [comment]
You're right! Looks like most/all of my series and tags links are broken. Thanks for the heads up! 

The theme I use manages most of this logic - so either I'm misusing something or the theme has a bug.

**Comment by brandtkeller** [comment]
Update: the URL it was redirecting to previously was incorrect - tags and series should now be functional.
